name: Build and Release Windows App

on:
  push:
    tags:
      - 'win-v*'

jobs:
  release:
    runs-on: windows-latest
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Next.js
        run: npm run next:build
      
      - name: Build Electron
        run: npm run electron:build
      
      # 빌드 및 배포 (Windows)
      - name: Build and release for Windows
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN || secrets.GH_TOKEN }}
        run: |
          npx electron-builder --win --publish always
      
      # 생성된 아티팩트 업로드
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: |
            dist/*.exe
            releases/*.exe
          if-no-files-found: ignore 